
export default {
    white: "#FFFFFF",
    black: "#000000",
    darkGray: "#6a7475",
    lightGray: "#D3D3D3",
    primary: "#0c707d",
    secondary: "#1ea8ba",
    success: "#0b4219",
    warning: "#bfbf22",
    danger: "#b52012",
    blue: "#4285F4",
    love: '#ff0a04',
    // homeScreenGradientBackground: ["#f2fcfc", "#e1f8fa"],
    statusBarColor: "#e1e2ff",
    homeScreenGradientBackground: ["#b2f5ff", "#f4ffcf"],
    searchScreenGradientBackground: ["#f8faf5", "#effadc"],
    GPTScreenGradientBackground: ["#f5f6fa", "#dae1f5"],
    servicesOfferedScreenGradientBackground: ["#c8e0ff","#fad1ff"],
    accountScreenGradientBackground: ["#fcf6f5", "#fae6e1"],
}